# Generated by Django 4.2.3 on 2023-07-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0002_course_video_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('announcements', models.TextField()),
                ('events', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
    ]
